/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author mirismr
 */
public class LabelSetPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabelSetPanel
     */
    
    private List<String> labels;
    
    public LabelSetPanel(List<String> labels) {
        initComponents();
        this.labels = labels;
        for(String l : labels) {
            JLabel label = new JLabel(l);
            
            this.add(label);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
